version: '3.9'

services:
  opalmind-api:
    image: ${OPALMIND_IMAGE:-ghcr.io/authorityab/opalmind-api:latest}
    env_file:
      - stack.env
    environment:
      - NODE_ENV=production
      - MATOMO_BASE_URL=${MATOMO_BASE_URL:?missing_MATOMO_BASE_URL}
      - MATOMO_TOKEN=${MATOMO_TOKEN:?missing_MATOMO_TOKEN}
      - MATOMO_DEFAULT_SITE_ID=${MATOMO_DEFAULT_SITE_ID:-}
      - OPAL_BEARER_TOKEN=${OPAL_BEARER_TOKEN:?missing_OPAL_BEARER_TOKEN}
    ports:
      - "3000:3000"
    restart: unless-stopped
